commitizen:
  name: cz_conventional_commits
  # Don't manage version here - Release Please handles it
  version_provider: pep621
  update_changelog_on_bump: false
  tag_format: v$version
  version_scheme: semver
  version_files: []  # Empty - no version files to update
  bump_message: "bump: version $current_version → $new_version"

  # Commit message template
  template: |
    $type{% if scope %}({{ scope }}){% endif %}{% if breaking %}!{% endif %}: {{ subject }}
    {% if body %}
    {{ body }}
    {% endif %}
    {% if footer %}
    {{ footer }}
    {% endif %}

  # Commit types for your OpenLDAP container project
  commit_parser: '^(?P<change_type>feat|fix|docs|style|refactor|test|build|ci|chore|revert)(?:\((?P<scope>[^()\r\n]*)\))?(?P<breaking>!)?:\s(?P<message>.*)$'

  change_type_map:
    feat: Features
    fix: Bug Fixes
    docs: Documentation
    style: Code Style
    refactor: Code Refactoring
    test: Tests
    build: Build System
    ci: CI/CD
    chore: Maintenance
    revert: Reverts

  schema: |
    <type>(<scope>): <subject>
    <BLANK LINE>
    <body>
    <BLANK LINE>
    <footer>

  schema_pattern: '^(feat|fix|docs|style|refactor|test|build|ci|chore|revert)(\([a-z \-]+\))?(!)?: .{1,50}'

  info: |
    ## OpenLDAP Futurama Container Commit Guidelines

    ### Type
    - feat: New feature (LDAP schema, functionality)
    - fix: Bug fix or security patch
    - docs: Documentation changes
    - chore: Maintenance (dependencies, CI, Docker)
    - refactor: Code restructuring

    ### Scope (optional)
    - ldap: LDAP configuration changes
    - docker: Dockerfile/container changes
    - ci: GitHub Actions workflow changes
    - security: Security-related changes
    - data: Test data changes

    ### Examples:
    - feat(ldap): add memberOf overlay support
    - fix(security): patch container vulnerabilities
    - chore(docker): update base image to latest
    - docs: update README with new configuration options

  questions:
    - type: list
      name: change_type
      message: "Select the type of change you are committing:"
      choices:
        - value: feat
          name: "feat: ✨ A new feature"
          key: f
        - value: fix
          name: "fix: 🐛 A bug fix"
          key: x
        - value: docs
          name: "docs: 📚 Documentation only changes"
          key: d
        - value: chore
          name: "chore: 🔧 Changes to build process or auxiliary tools"
          key: c
        - value: refactor
          name: "refactor: ♻️  A code change that neither fixes a bug nor adds a feature"
          key: r
        - value: test
          name: "test: ✅ Adding missing tests or correcting existing tests"
          key: t
        - value: build
          name: "build: 👷 Changes that affect the build system or external dependencies"
          key: b
        - value: ci
          name: "ci: 🎡 Changes to CI configuration files and scripts"
          key: i

    - type: input
      name: scope
      message: "Scope (optional, e.g., ldap, docker, ci, security):"

    - type: input
      name: subject
      message: "Short description:"

    - type: input
      name: body
      message: "Longer description (optional):"

    - type: confirm
      name: is_breaking_change
      message: "Are there any breaking changes?"
      default: false

    - type: input
      name: footer
      message: "Footer (optional, e.g., closes #123):"
