services:
  openldap-futurama:
    build: .
    container_name: openldap-futurama
    hostname: ldap.planetexpress.com
    ports:
      - "389:389"
    volumes:
      - ldap_data:/var/lib/openldap
      - ldap_config:/etc/openldap/slapd.d
    networks:
      - ldap_net
    restart: unless-stopped

  phpldapadmin:
    image: phpldapadmin/phpldapadmin:latest
    container_name: phpldapadmin
    environment:
      - LDAP_HOST=openldap-futurama
      - LDAP_BASE_DN=dc=planetexpress,dc=com
      - LDAP_USERNAME=cn=admin,dc=planetexpress,dc=com
      - LDAP_PASSWORD=GoodNewsEveryone
    ports:
      - "8080:8080"
    depends_on:
      - openldap-futurama
    networks:
      - ldap_net
    restart: unless-stopped

volumes:
  ldap_data:
    driver: local
  ldap_config:
    driver: local

networks:
  ldap_net:
    driver: bridge
