name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build Docker image
      run: |
        docker build -t openldap-futurama:latest .
        
    - name: Start test container
      run: |
        docker run -d --name openldap-test -p 3890:389 openldap-futurama:latest
        
    - name: Wait for LDAP to be ready
      run: |
        echo "Waiting for LDAP to initialize..."
        for i in {1..30}; do
          if docker exec openldap-test ldapsearch -x -H ldap://localhost \
             -D "cn=admin,dc=planetexpress,dc=com" -w "GoodNewsEveryone" \
             -b "dc=planetexpress,dc=com" -s base "(objectclass=*)" 2>/dev/null; then
            echo "LDAP is ready!"
            break
          fi
          echo "Waiting... ($i/30)"
          sleep 2
        done
        
    - name: Test LDAP functionality
      run: |
        echo "Testing user search..."
        docker exec openldap-test ldapsearch -x -H ldap://localhost \
          -D "cn=admin,dc=planetexpress,dc=com" -w "GoodNewsEveryone" \
          -b "dc=planetexpress,dc=com" "(uid=fry)" cn sAMAccountName
        
        echo "Testing AD groups..."
        docker exec openldap-test ldapsearch -x -H ldap://localhost \
          -D "cn=admin,dc=planetexpress,dc=com" -w "GoodNewsEveryone" \
          -b "ou=groups,dc=planetexpress,dc=com" "(objectClass=group)" cn groupType
        
        echo "Testing memberOf..."
        docker exec openldap-test ldapsearch -x -H ldap://localhost \
          -D "cn=admin,dc=planetexpress,dc=com" -w "GoodNewsEveryone" \
          -b "dc=planetexpress,dc=com" "(uid=amy)" memberOf
          
    - name: Security scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'openldap-futurama:latest'
        format: 'table'
        severity: 'CRITICAL,HIGH'
        exit-code: 0  # Don't fail on vulnerabilities for now
        
    - name: Cleanup
      if: always()
      run: |
        docker stop openldap-test || true
        docker rm openldap-test || true