name: CI

on:
  push:
    branches-ignore: [ main ]
  pull_request:
    branches: [ main ]
  workflow_call:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: |
        docker build -t openldap-futurama:latest .
        docker images | grep openldap-futurama

    - name: Start container
      run: |
        docker run --rm -d -p 389:389 --name openldap-futurama openldap-futurama:latest
        sleep 2
        docker ps | grep openldap-futurama || (echo "Container failed to start" && docker logs openldap-futurama && exit 1)

    - name: Wait for LDAP to be ready
      env:
        LDAP_ADMIN_PASSWORD: ${{ secrets.LDAP_ADMIN_PASSWORD }}
      run: |
        timeout=60
        while [ $timeout -gt 0 ]; do
          if docker exec openldap-futurama ldapsearch -x -H ldap://localhost -D "cn=admin,dc=planetexpress,dc=com" -w "$LDAP_ADMIN_PASSWORD" -b "dc=planetexpress,dc=com" -s base "(objectclass=*)" 2>/dev/null; then
            echo "LDAP is ready!"
            break
          fi
          echo "Waiting for LDAP... ($timeout seconds remaining)"
          sleep 2
          timeout=$((timeout-2))
        done

        if [ $timeout -le 0 ]; then
          echo "LDAP failed to start within timeout period"
          docker logs openldap-futurama
          exit 1
        fi

    - name: Test LDAP functionality
      env:
        LDAP_ADMIN_PASSWORD: ${{ secrets.LDAP_ADMIN_PASSWORD }}
      run: |
        echo "Testing basic user search..."
        docker exec openldap-futurama ldapsearch -x -H ldap://localhost -D "cn=admin,dc=planetexpress,dc=com" -w "$LDAP_ADMIN_PASSWORD" -b "dc=planetexpress,dc=com" "(uid=fry)" cn

        echo "Testing AD attributes..."
        docker exec openldap-futurama ldapsearch -x -H ldap://localhost -D "cn=admin,dc=planetexpress,dc=com" -w "$LDAP_ADMIN_PASSWORD" -b "dc=planetexpress,dc=com" "(sAMAccountName=fry)" cn

        echo "Testing memberOf overlay..."
        docker exec openldap-futurama ldapsearch -x -H ldap://localhost -D "cn=admin,dc=planetexpress,dc=com" -w "$LDAP_ADMIN_PASSWORD" -b "dc=planetexpress,dc=com" "(uid=amy)" memberOf

    - name: Scan Docker image for vulnerabilities
      uses: aquasecurity/trivy-action@0.32.0
      with:
        image-ref: 'openldap-futurama:latest'
        format: 'table'
        severity: 'CRITICAL,HIGH'
        exit-code: 1

    - name: Cleanup
      if: always()
      run: |
        docker stop openldap-futurama || true
