name: Release

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.0.0
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., v1.0.0)'
        required: true
        type: string

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
    
  release:
    needs: ci
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build and push multi-arch Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ghcr.io/${{ github.repository }}:${{ github.event.inputs.version || github.ref_name }}
          ghcr.io/${{ github.repository }}:latest
        
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.event.inputs.version || github.ref_name }}
        name: Release ${{ github.event.inputs.version || github.ref_name }}
        body: |
          ## OpenLDAP Futurama ${{ github.event.inputs.version || github.ref_name }}
          
          AD-compatible LDAP test server with Futurama theme.
          
          ### Docker Image
          ```bash
          docker pull ghcr.io/${{ github.repository }}:${{ github.event.inputs.version || github.ref_name }}
          ```
          
          ### Quick Start
          ```bash
          docker run -d -p 389:389 ghcr.io/${{ github.repository }}:${{ github.event.inputs.version || github.ref_name }}
          ```
          
          See [README](https://github.com/${{ github.repository }}) for full documentation.
        draft: false
        prerelease: false