name: Release Please

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      release-type:
        description: 'Type of release'
        required: true
        default: 'patch'
        type: choice
        options:
        - patch
        - minor
        - major

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
    secrets: inherit

  release-please:
    needs: ci
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: simple
          token: ${{ secrets.GITHUB_TOKEN }}

  build-and-push:
    needs: release-please
    if: needs.release-please.outputs.release_created
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push multi-platform image
      uses: docker/build-push-action@v6
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ghcr.io/imandrew/openldap-futurama:${{ needs.release-please.outputs.tag_name }}
          ghcr.io/imandrew/openldap-futurama:latest
        labels: |
          org.opencontainers.image.title=openldap-futurama
          org.opencontainers.image.description=OpenLDAP server with Planet Express test data and AD compatibility
          org.opencontainers.image.source=https://github.com/imandrew/openldap-futurama
          org.opencontainers.image.version=${{ needs.release-please.outputs.tag_name }}
          org.opencontainers.image.revision=${{ github.sha }}
