name: Security Scan

on:
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch: # Allow manual trigger

jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Build Docker image
      run: docker build -t openldap-futurama:test .
      
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@0.32.0
      with:
        image-ref: 'openldap-futurama:test'
        format: 'sarif'
        output: 'trivy-results.sarif'
        severity: 'CRITICAL,HIGH,MEDIUM'
        
    - name: Upload Trivy results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: 'trivy-results.sarif'
        
    - name: Run Trivy in table format for summary
      uses: aquasecurity/trivy-action@0.32.0  
      with:
        image-ref: 'openldap-futurama:test'
        format: 'table'
        severity: 'CRITICAL,HIGH'
        exit-code: 0  # Don't fail, just report